run:
	python manage.py runserver
shell:
	python manage.py shell
migrations:
	python manage.py makemigrations
migrate:
	python manage.py migrate
superuser:
	python manage.py createsuperuser
test:
	python manage.py test